# Generated by Django 4.2.30 on 2026-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0003_alter_answer_id_alter_checkquestion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
