# Generated by Django 4.2.30 on 2026-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0004_meeting_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='record',
            field=models.TextField(blank=True),
        ),
    ]
