# Generated by Django 4.2.30 on 2026-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0005_meeting_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
