# Generated by Django 4.2.30 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0007_meeting_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
