# Generated by Django 4.2.30 on 2026-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0008_meeting_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='processing_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
