# Generated by Django 4.2.30 on 2026-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0009_meeting_processing_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkquestion',
            constraint=models.UniqueConstraint(fields=('meeting', 'order'), name='unique_check_question_order'),
        ),
    ]
